# Caution: This workflow is internal to the php-windows-builder repository.
# Do not copy this workflow to your repository.
# Instead, refer to the workflows in the examples/ directory.

name: Build PHP Extension From PECL
run-name: Build PHP Extension ${{ inputs.extension-url }}, ${{ inputs.extension-ref }}
on:
  workflow_dispatch:
    inputs:
      extension-url:
        description: 'Extension URL'
        required: true
      extension-ref:
        description: 'Extension ref'
        required: true
      php-version-list:
        description: 'PHP versions to build'
        required: false
      arch-list:
        type: choice
        options: ['x64', 'x86', 'x64,x86']
        description: 'Architectures to build'
        required: false
        default: 'x64,x86'
      ts-list:
        type: choice
        options: ['nts', 'ts', 'nts,ts']
        description: 'Thread safety to build'
        required: false
        default: 'nts,ts'
      args:
        description: 'Configure arguments'
        required: false
      libs:
        description: 'Libraries'
        required: false
      run-tests:
        type: choice
        options: ['true', 'false']
        description: 'Run tests after building the extension'
        required: false
        default: 'false'
      test-runner:
        description: 'Test runner to use'
        required: false
        default: 'run-tests.php'
      test-runner-args:
        description: 'Arguments for the test runner'
        required: false
jobs:
  get-extension-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.extension-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Get the extension matrix
        id: extension-matrix
        uses: ./extension-matrix
        with:
          extension-url: ${{ inputs.extension-url }}
          extension-ref: ${{ inputs.extension-ref }}
          php-version-list: ${{ inputs.php-version-list }}
          arch-list: ${{ inputs.arch-list }}
          ts-list: ${{ inputs.ts-list }}

  extension:
    needs: get-extension-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.get-extension-matrix.outputs.matrix)}}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build the extension
        uses: ./extension
        with:
          extension-url: ${{ inputs.extension-url }}
          extension-ref: ${{ inputs.extension-ref }}
          php-version: ${{ matrix.php-version }}
          arch: ${{ matrix.arch }}
          ts: ${{ matrix.ts }}
          args: ${{ inputs.args }}
          libs: ${{ inputs.libs }}
          run-tests: ${{ inputs.run-tests }}
          test-runner: ${{ inputs.test-runner }}
          test-runner-args: ${{ inputs.test-runner-args }}
          build-directory: C:\build
        env:
          artifact-naming-scheme: pecl
          auto-detect-args: true
          auto-detect-libs: true
          no-debug-symbols-ddtrace: true

  artifact:
    runs-on: ubuntu-latest
    needs: extension
    outputs:
      artifact-id: ${{ steps.artifact.outputs.artifact-id }}
    steps:
      - name: Upload artifact
        uses: actions/upload-artifact/merge@v5
        id: merge
        with:
          name: artifact
          delete-merged: true

      - name: Get merged artifact
        uses: actions/download-artifact@v5
        with:
          name: artifact
          path: artifact

      - name: Remove merged artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh api --method DELETE "repos/${{ github.repository }}/actions/artifacts/${{ steps.merge.outputs.artifact-id }}"

      - name: Stage artifact for release
        id: stage
        run: |
          extension=$(basename "${{ inputs.extension-url }}" | tr '[:upper:]' '[:lower:]')
          mkdir -p /tmp/$extension/$extension/${{ inputs.extension-ref }}/
          cp -a artifact/* /tmp/$extension/$extension/${{ inputs.extension-ref }}/          
          echo "artifact-name=$extension-${{ inputs.extension-ref }}" >> "$GITHUB_OUTPUT"
          echo "artifact-path=/tmp/$extension" >> "$GITHUB_OUTPUT"

      - name: Upload zip
        uses: actions/upload-artifact@v5
        id: artifact
        with:
          name: ${{ steps.stage.outputs.artifact-name }}
          path: ${{ steps.stage.outputs.artifact-path }}

  upload:
    runs-on: ubuntu-latest
    needs: artifact
    steps:
      - name: Upload to downloads server
        run: |
          extension=$(basename "${{ inputs.extension-url }}")
          url="https://api.github.com/repos/${{ github.repository }}/actions/artifacts/${{ needs.artifact.outputs.artifact-id }}/zip"
          gh workflow run pecl.yml -R php/web-downloads -f url="$url" -f extension="$extension" -f ref="${{ inputs.extension-ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.WINDOWS_BUILDS_TOKEN }}
